[id="concepts"]
= Concepts

To start with Lookyloo there are some concepts a user should be familiar with.

== Cookies
A *cookie* is a small amount of data generated by a website that the backend can store in the user's browsers. Cookies are used for user tracking, personalization, and authentication. To learn more, read about link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies[Using HTTP cookies].

[NOTE]
You can initiate a capture with existing cookies, see xref:ROOT:capture-cookies.adoc[cookies documentation].

== Referer
The HTTP *Referer* header is a type of request header that identifies the address of a previous web page that links to a current web page or requested resource. It allows websites and web servers to identify where the traffic is coming from. The usage of the referer header increases the risk of privacy and security issues on a website. To learn more, read about the link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer[Referer header].

[NOTE]
You can initiate a capture with a referer.

== iframe
An Inline Frame (*iframe*) is a component of an HTML element that allows documents, videos, and other media to be embedded within a page. The <iframe> tag defines a region within a document, in which the browser can display a separate document. The <iframe> tag specifies an inline frame, which is used to embed another document within an HTML document. To learn more, read about link:https://www.w3schools.com/html/html_iframe.asp[HTML iframes].

== Redirect
HTTP allows servers to *redirect* a request to a different location. A server specifies redirection by returning a _3xx_ status code. A redirect places instructions on the server to provide something different then the original request. To learn more, read about link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections#:~:text=In%20HTTP%2C%20redirection%20is%20triggered,provided%20in%20the%20Location%20header.[redirections in HTTP].

== User-Agent
The *User-Agent* is a request header that allows network protocol peers to identify information about the web server. User agents are unique to every visitor on the web. The User-Agent string reveals a catalog of technical data and contains the user application or software, the operating system, versions, the web client, the web client's version, and the engine responsible for the content display. To learn more, read about the link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent[User-Agent request header].

== HTTP Response Status Code
When a request is made to a web server, a three digit *HTTP response status code* is returned. HTTP response status codes indicate whether a specific HTTP request has been successfully completed. To learn more, read about link:https://developer.mozilla.org/en-US/docs/Web/HTTP/Status[HTTP response status codes].

== CNAME record

Type of https://en.wikipedia.org/wiki/CNAME_record[DNS record] that create an alias from one domain name to an other one. It is also often used in a technique called https://medium.com/nextdns/cname-cloaking-the-dangerous-disguise-of-third-party-trackers-195205dc522a[CNAME Cloaking] to bypass the blocking of 3rd party cookies.
