[id="contributor-guide"]
= Contributing to Lookyloo

**You can contribute by:**

* Raising an issue you find in the code or documentation
* Fixing issues by opening a pull request
* Improving documentation or code samples

All bugs, tasks or enhancements are tracked as link:https://https://github.com/Lookyloo/lookyloo/issues/new/choose[GitHub issues]. Use labels to indicate requirements and information related to the reported issue.

== Contributor Behavior

Examples of behavior that contributes to creating a positive environment include:

* Using welcoming and inclusive language
* Focusing on what is best for the community
* Being respectful of differing viewpoints and experiences
* Gracefully accepting constructive criticism

Please read our xref:code-conduct.adoc[Code of Conduct].


== Before You Begin

* link:https:[Get started] by installing and getting familiar with link:https://git-scm.com/doc[Git].
* Use link:https:https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc] to contribute to Lookyloo documentation.
* Refer to our link:https:[style guide] for guidance on formatting your documentation contributions.


== General Information

Thank you for your contributions. To start contributing to Lookyloo:

. Create an issue describing your proposed change to the repository.

. The repository owners will triage and respond to your issue promptly.

. Fork the repository.

. Submit a pull request with the proposed changes. The required format for the Git commit message is "Issue # <Issue ID> - <issue_message>".


== Raising an Issue

GitHub issues can be used to report bugs or submit feature requests.

When reporting an issue, you can use the link:https://github.com/Lookyloo/lookyloo/issues/new/choose[applicable issue reporting template]. Issues should be raised in the corresponding repository.

 * link:https://github.com/Lookyloo/docs/issues[Changes to code]
 * link:https://github.com/Lookyloo/lookyloo/issues[Changes to documentation for website]
 * link:https://github.com/Lookyloo/PyLookyloo/issues[Changes to PyLooklyloo (CLI)]

Please include the following information when creating an issue:

* Operating system you are using
* The steps needed to reproduce the issue.


== Submit a Pull Request

Make a pull request (PR) to add content to the repository. When making a PR, ensure you include:

* A description of what the PR fixes
* Associated Issue # and Issue title (if applicable)
* Operating system you are using

See the xref:contributor-git.adoc[using Git documentation] for more information on using Git and making pull requests.


