[id="Lookyloo-main"]
= Lookyloo

[IMPORTANT]
====
This site is a work in progress
====

With Lookyloo you can dissect a website while it is in motion.

Lookyloo is a web interface that captures a webpage and then displays a tree of the domains, that call each other.

== What is a Lookyloo?

Per the definition on link:https://www.urbandictionary.com/define.php?term=lookyloo[Urban Dictionary]:

. People who just come to look.
. People who go out of their way to look at people or something often causing crowds and more disruption.
. People who enjoy staring at or watching other people's misfortune. Oftentimes car onlookers to car accidents.

Same as Looky Lou; often spelled as Looky-loo (hyphen) or lookylou.
In L.A. usually the lookyloos cause more accidents by not paying full attention to what is ahead of them.

== What is Lookyloo?

More seriously, xref:lookyloo-explained.adoc[have a look] at what lookyloo is, and at some of our xref:use-cases.adoc[use cases].

== Learn More

Read through our documentation for more information. Please also visit our link:https://github.com/Lookyloo/Lookyloo[GitHub repo] and join our link:https://github.com/Lookyloo[organization].


== Follow us

Check out our public instance at https://lookyloo.circl.lu/

* link:https://github.com/Lookyloo[Lookyloo Organization on GitHub]
* link:https://github.com/Lookyloo/Lookyloo[Lookyloo Repository]
* link:https://twitter.com/lookyloo_app[Twitter]


