[id="install-lookyloo"]
= Install Lookyloo

[IMPORTANT]
====
Requires Python 3.8 or higher (3.12 prefered), expects Ubuntu 22.04 or more recent (24.04 prefered).
====

== Install Lookyloo Dependencies

=== Install Poetry

link:https://python-poetry.org/[Poetry] handles dependency installation
as well as building and packaging of Python packages.

See the link:https://python-poetry.org/docs/#installation[installation guide] for more details.

=== Install Valkey

NOTE: Lacus supports valkey or redis, but valkey is prefered now due to the change of license.

link:https://valkey.io/[Valkey]: An open source (BSD licensed), in-memory data structure
store, used as a database, cache and message broker.

NOTE: Valkey should be installed from the source, and the repository must be in
the same directory as the one you will be cloning Lookyloo in to.

NOTE: Since Lookyloo 1.25, valkey 7.2 is required.

In order to compile and test valkey, you will need a few packages:

```bash
sudo apt-get update
sudo apt install build-essential tcl
```

```bash
git clone https://github.com/valkey-io/valkey
cd valkey
git checkout 7.2
make
# Optionally, you can run the tests:
make test
cd ..
```

== Install Lookyloo

=== Prerequisites

* Poetry is installed.
* Valkey is installed from the source. The repository must be in the same directory
  as the one you will be cloning Lookyloo in to.


* Python3 development package

```bash
sudo apt install python3-dev
```

=== Procedure

. Clone the Lookyloo repository.
+
```bash
git clone https://github.com/Lookyloo/lookyloo.git
```

The directory tree must look like that:

```
.
├── valkey  => cloned valkey
└── lookyloo => cloned lookyloo
```

. Change directory
+
```
cd lookyloo
```

. Run the commands:
+
```
poetry install
echo LOOKYLOO_HOME="'`pwd`'" > .env
```

. Install the dependencies for playwright (requires sudo), and the browsers:

```
poetry shell
playwright install-deps
playwright install
```

== Configuration

. Initialize the user configuration
+
```bash
cp config/generic.json.sample config/generic.json
cp config/modules.json.sample config/modules.json
```

. Edit the config files accordingly to your needs: see the `_notes` key in the JSON file.
  You can also look at the xref:lookyloo-integration.adoc[integration page] for more information regarding the modules,
  and the xref:lookyloo-configuration.adoc[configuration page] for the generic configuration options.

. Make sure the configuration files are valid, and pull the 3rd party dependencies for the website
+
```bash
poetry run update --yes
```

== Run the app

```bash
poetry run start
```

== Open the website

Unless you changed the default in `config/generic.json`, the web interface will be reachable at `http://0.0.0.0:5100/`


=== Install uwhoisd (Optional)

In order to use the Universal Whois you have to install uwhoisd from Lookyloo repository and the whois package:

```bash
sudo apt-get update
sudo apt-get install whois
```

```bash
git clone https://github.com/Lookyloo/uwhoisd
cd uwhoisd
poetry install
echo UWHOISD_HOME="'`pwd`'" > .env
poetry run start
```

==== Configure services (Optional)

```

Then configure the service file
```bash
nano etc/systemd/system/uwhoisd.service.sample
```

```bash
sudo cp etc/systemd/system/uwhoisd.service.sample /etc/systemd/system/uwhoisd.service
cd ..
sudo systemctl daemon-reload
sudo systemctl start uwhoisd
sudo systemctl status uwhoisd
```

If everything is ok, activate the service for reboot
```bash
sudo systemctl enable uwhoisd
```

