[id="install-lookyloo-production"]

= Run Lookyloo in Production

[IMPORTANT]
Please follow the xref:install-lookyloo.adoc[default installation guide] first.

== Reverse Proxy (Nginx)

```bash
pip install uwsgi
```

== Configuration Files

You have to configure the two following files:

* `etc/nginx/sites-available/lookyloo`
* `etc/systemd/system/lookyloo.service`

Copy them to the appropriate directories, and run the following command:
```bash
sudo ln -s /etc/nginx/sites-available/lookyloo /etc/nginx/sites-enabled
```

If needed, remove the default site
```bash
sudo rm /etc/nginx/sites-enabled/default
```

Make sure everything is working:

```bash
sudo systemctl start lookyloo
sudo systemctl enable lookyloo
sudo nginx -t
# If it is cool:
sudo service nginx restart
```

And you can open ```http://<IP-or-domain>/```

Now, you should configure
link:https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04[TLS (let's encrypt and so on)]


== Multi-users App

Use aquarium for a reliable multi-users app

Aquarium is a haproxy + splash bundle that will allows Lookyloo to be used by more than one user at a time.

The initial version of the project was created by link:https://github.com/TeamHG-Memex/aquarium[TeamHG-Memex], but we have a link:https://github.com/Lookyloo/aquarium[dedicated repository] that fits our needs better.

Follow the link:https://github.com/Lookyloo/aquarium/blob/master/README.rst[documentation] if you want to use it.
