[id="install-lookyloo"]
= Install Lookyloo

[IMPORTANT]
====
Requires Python 3.8 or higher, expects Ubuntu 20.04 or more recent.
====

== Install Lookyloo Dependencies

=== Install Poetry

link:https://python-poetry.org/[Poetry] is tool to handle dependency installation
as well as building and packaging of Python packages.

```bash
curl -sSL https://install.python-poetry.org | python3 -
```

More details in the the link:https://github.com/python-poetry/poetry/#installation[installation guide].

=== Install Redis

link:https://redis.io/[Redis]: An open source (BSD licensed), in-memory data structure
store, used as a database, cache and message broker.

NOTE: Redis should be installed from the source, and the repository must be in
the same directory as the one you will be cloning Lookyloo in to.

In order to compile and test redis, you will need a few packages:

```bash
sudo apt-get update
sudo apt install build-essential tcl
```

```bash
git clone https://github.com/redis/redis.git
cd redis
git checkout 6.2
make
# Optionally, you can run the tests:
make test
cd ..
```

=== Install uwhoisd (Optional)

In order to use the Universal Whois you have to install uwhoisd from Lookyloo repository and the whois package:

```bash
sudo apt-get update
sudo apt-get install whois
```

```bash
git clone https://github.com/Lookyloo/uwhoisd
cd uwhoisd
poetry install
```

Then configure the service file
```bash
nano etc/systemd/system/uwhoisd.service.sample
```

```bash
sudo cp etc/systemd/system/uwhoisd.service.sample /etc/systemd/system/uwhoisd.service
cd ..
sudo systemctl daemon-reload
sudo systemctl start uwhoisd
sudo systemctl status uwhoisd
```

If everything is ok, activate the service for reboot
```bash
sudo systemctl enable uwhoisd
```

== Install Lookyloo

=== Prerequisites

* Poetry is installed.
* Redis is installed from the source. The repository must be in the same directory
  as the one you will be cloning Lookyloo in to.

* Python3 development package

```bash
sudo apt install python3-dev
```

* Dependencies for link:https://playwright.dev/python/docs/intro#installation[playwright]:

```bash
sudo apt install libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxdamage1 libgbm1 libpango-1.0-0 libcairo2 libatspi2.0-0
```


=== Procedure

. Clone the Lookyloo repository.
+
```bash
git clone https://github.com/Lookyloo/lookyloo.git
```

. Change directory
+
```
cd lookyloo
```

. Run the commands:
+
```
poetry install
echo LOOKYLOO_HOME="'`pwd`'" > .env
```

NOTE: If you have error messages about python 2.7, it is an issue with poetry,
and the quick and dirty fix is to edit `~/.poetry/bin/poetry` and add a `3` at the end of the line:

  #!/usr/bin/env python3

instead of

  #!/usr/bin/env python

=== Install pymisp dependencies (optional)
If you want to install the pymisp dependencies, please install libfuzzy-dev and the run poetry with -E option
```bash
sudo apt-get install libfuzzy-dev
poetry install -E misp
```

== Configuration

. Initialize the user configuration
+
```bash
cp config/generic.json.sample config/generic.json
cp config/modules.json.sample config/modules.json
```

. Edit the config files accordingly to your needs: see the `_notes` key in the JSON file.
  You can also look at the xref:lookyloo-integration.adoc[integration page] for more information regarding the modules,
  and the xref:lookyloo-configuration.adoc[configuration page] for the generic configuration options.

. Make sure the configuration files are valid, and pull the 3rd party dependencies for the website
+
```bash
poetry run update --yes
```

== Run the app

```bash
poetry run start
```

== Open the website

Unless you changed the default in `config/generic.json`, the web interface will be reachable at `http://0.0.0.0:5100/`
