= Run Lookyloo with a Simple Docker Setup

[IMPORTANT]
This documentation is currently non-functional, and the docker files need to be updated.
See link:https://github.com/Lookyloo/lookyloo/issues/94[this issue] for more details.

== Dockerfile

The repository includes a [Dockerfile](Dockerfile) for building a containerized instance of the app.

Lookyloo stores the scraped data in /lookyloo/scraped. If you want to persist the scraped data between runs it is sufficient to define a volume for this directory.


== Running a Complete Setup with Docker Compose

Additionally you can start a complete setup, by using Docker Compose and the
included service definition in [docker-compose.yml](docker-compose.yml) with:

```
docker-compose up
```

After building and startup is complete lookyloo should be available at link:
http://localhost:5000/[http://localhost:5000/].

If you want to persist the data between different runs uncomment  the "volumes" definition in the last two lines of [docker-compose.yml](docker-compose.yml) and define a data storage directory in your Docker host system there.
