[id="install-lookyloo"]
= Install Lookyloo

[IMPORTANT]
====
Poetry, Redis, and Splash, must be installed before you begin installation of Lookyloo. For information on installing these components see the documentation on xref:install-dependencies.adoc[installing dependencies].
====

== Prerequisites
* Poetry is installed.
* Redis is installed from the source. The repository should be in the same directory as the one you will be cloning Lookyloo in to.
* Splash is installed.

== Procedure

. To install, clone the Lookyloo repository.
+
```bash
git clone https://github.com/Lookyloo/lookyloo.git
```

. Change directory
+
```
cd lookyloo
```

. Run the commands:
+
```
poetry install
echo LOOKYLOO_HOME="'`pwd`'" > .env
```

== Configuration

. Initialize the user configuration
+
```bash
cp config/generic.json.sample config/generic.json
cp config/modules.json.sample config/modules.json
```

. Edit the config files accordingly: see the `_notes` key in the JSON file.

. Make sure the configuration files are valid, and pull the 3rd party dependencies for the website
+
```bash
poetry run update.py --yes
```


== Run Splash

* From another terminal, run the following command:

```bash
sudo docker run -p 8050:8050 -p 5023:5023 scrapinghub/splash --disable-browser-caches
# On a server with a decent amount of RAM, you may want to run it this way:
# sudo docker run -p 8050:8050 -p 5023:5023 scrapinghub/splash -s 100 -m 50000 --disable-browser-caches
```

== Run the app

```bash
poetry run start.py
```
