[id="use-cases"]
= Lookyloo Use Cases

Using Lookyloo, you can extract data from a webpage so it can be assessed and visualized.

Data obtained by web scraping can be used in a variety of ways.  For example, data is collected from various video sharing sites and then collated on one site so that you can compare, like, and comment on content.


*Use Lookyloo to:*

* Observe who has access to your information when you visit a site
* Identify malicious activity
* Recognize phishing activity
* Pinpoint lapses in security and flag suspicious behavior 


Lookyloo can be used by various professionals, including...

== Journalists

As a *journalist*, I can uses Lookyloo to ...

* Do this thing
* Do that thing 


== Legal Professionals 

As a *legal professional*, I can use Lookyloo to ...


== Site Administrators

As a *site administrator*, I can use Lookyloo to ...


== Forensic Investigators

As a *forensic investigator*, I can use Lookyloo to ...


== Educators

As an *educator*, I can use Lookyloo to ...
